version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
BeforeInstall:
    - location: /home/ubuntu/cicd_01_create_projdir.sh
      timeout: 3
      runas: root
ApplicationStart:
    - location: creditods/cicd_01_create_projdir.sh
      timeout: 3
      runas: root
  
