version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
BeforeInstall:
    - location: /cicd_01_create_projdir.sh
      timeout: 3
      runas: root
ApplicationStart:
    - location: /creditODS/cicd_01_create_projdir.sh
      timeout: 3
      runas: root
  
