version: 0.2

phases:
  install:
    runtime-versions:
     python: 3.7
    commands:
      - pip install --upgrade pip
     
pre_build:
  commands:
    - python --version
   
post_build:
  commands:
   
artifacts:
  files:
    - '**/*'
